# Generated by Django 4.2.1 on 2023-06-19 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='product_img')),
                ('cat_no', models.CharField(max_length=10)),
                ('cas_no', models.CharField(max_length=10)),
                ('mol_formula', models.CharField(max_length=50)),
                ('inv_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rfq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=10)),
                ('package', models.IntegerField(max_length=3)),
                ('package_unit', models.CharField(choices=[('1', 'MG'), ('1', 'G'), ('1', 'KG')], default='1', max_length=2)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
