# Generated by Django 4.2.1 on 2023-06-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cas_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to='static/product_img'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='package',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='package_unit',
            field=models.CharField(choices=[('MG', 'MG'), ('G', 'G'), ('KG', 'KG')], default='MG', max_length=2),
        ),
    ]
